name: expecon
channels:
  - conda-forge
dependencies:
  - python=3.12
  - pip
  - numpy
  - scipy
  - matplotlib
  - pandas
  - scikit-learn
  - seaborn
  - jupyterlab
  - pyqt
  - mne
  - pip:
      - mne-icalabel
      - autoreject
      - neurokit2
      - neurodsp
      - nibabel