function s = setup
% s = setup returns the settings for run_exp.
%
% % Settings %
%
%   % General
%   s.rng_state    - state of random number generator (not mandatory)
%   s.file_prefix  - prefix for saving files (e.g., analog input recording)
%   s.blocks       - number of blocks
%   s.train_blocks - number of training blocks (prior to s.blocks)
%   s.train_cue_cond_n - training repetition of cued sub-blocks per condition
%   s.randomise_cues   - which cue color for which probability condition
%
%   % Cued sub-blocks
%   s.cue_cond     - cued likelihood of stimulation
%   s.cue_cond_n   - repetition of cued sub-blocks per condition 
%   s.cue_block_trials - number of trials per cued sub-blocks
%   s.cue_cond_t   - presentation duration of cued condition
%   s.feedback_t   - presentation duration of performance feedback after sub-blocks
%   s.feedback_cue_t - time between feedback and condition cue in s
%   s.show_feedback - turn feedback after sub-block on(1)/off(0)
%
%   % Stimuli   
%   s.near_d       - detection probability for stimulus s.stim_types(2)
%   s.near_name    - name for stimulus intensity in dialog
%   s.pulse_t      - duration of stimuls (rectangular pulse) in ms
%   s.pre_pulse_t  - duration of before stimulus (rectangular pulse) in ms
%   s.wave_t       - duration of waveform with rectangular pulse in ms
%   s.stim_dec     - number of decimal digits of intensity in mA (doc dlg_intensities)
%   s.stim_max     - maximum possible stimulus intensity in mA
%   s.TTL_t        - TTL pulse length (1 ms)
%   s.TTL_V        - TTL pulse amplitude (5 V)
% 
%   % Trial
%   s.get_flip_i   - number of samples for initial flip interval estimation with Screen('GetFlipInterval')
%   s.fix_t        - min/max vector for duration of fixation cross in s -> inter-trial interval
%   s.cue_t        - duration of stimulus cue in s
%   s.stim_delay   - stimulus delay in s
%   s.resp_window  - 'variable'/'fixed' - stop/continue after first button press
%   s.resp1_max_t  - maximum response time 1 in s
%   s.resp2_max_t  - maximum response time 2 in s
%   s.resp_p_min_t - minimum time left to show response pause screen in s
%
%   % Screen design
%   s.window_color - screen background rgb color vector
% 
%   % Text
%   s.txt_color    - text rgb color vector
%   s.txt_font     - font type
%   s.txt_size     - font size for response screens
%   s.cue_size     - font size for fix, cue and pause screens
% 
%   % Messages
%   s.fix          - fixation symbol (e.g., '+')
%   s.cue          - stimulus cue symbol (e.g., '~+~')
%   s.resp1_txt    - yes/no response text options, yes-no-order important, e.g. ['J'; 'N']
%   s.resp2_txt    - confidence response text options
%   s.resp1_offset - 1st response text offset left from screen center
%   s.ITI_cue      - inter trial interval symbol
%   s.pause_msg    - message on pause screen
% 
%   % Buttons
%   s.lpt_adr1     - parallel port address (see device manager - LPT1 details - resources)
%   s.lpt_adr2     - as above but 'I/O Range' #2
%   s.lpt_dir      - parallel port direction ('bi' or 'uni')
%   s.btn_resp1    - button codes for yes/no response
%   s.btn_resp2    - button codes for confidence response
%   s.btn_esc      - button code for quiting experiment
%
%   % Instruction
%   s.instr_dir    - instruction directory with condition subdirectories
%                     (relative to directory of nt_exp.m)
%   s.instr_subdir_wildcard    - instruction subdirectory wildcard
%   s.instr_img_wildcard       - filename wildcard of instruction image files
%
%
% Author:           Martin Grund
% Last update:      March 9, 2021

%% Settings

%% General
% s.rng_state = sum(100*clock); % If not defined, generated by run_exp
s.file_prefix = 'expecon_trial_';
s.blocks = 5;
s.train_blocks = 1;
s.train_cue_cond_n = [20 20];

% randomise cues between participants
s.randomise_cues = 0; % 1 == 0.25 = blue circle
%% localizer block
s.localizer_ntrials = 150;
s.localizer_isi = [1.2 1.8]; % 2 + (3-2) .* rand(s.localizer_ntrials,1);
s.supra_d = 0.9;
s.supra_name = 'Supra-threshold';

%% resting state block

s.resting_state_time = 360;

%% Cued sub-blocks
s.cue_cond = [0.25 0.75]; % cued likelihood of stimulation
s.cue_cond_n = [60 60]; % repetition of cued sub-blocks per condition 
s.prob_t = 1; % in s % how long should we show the condition cue?
s.feedback_t = 1; % in s % how long should we show the feedback cue?

s.feedback_after_trials = 30; % after how many trials do you want to give feedback
s.feedback_after_trials_train = 10; % after how many trials do you want to give feedback
s.show_feedback = 1; % 0 - off; 1 - on
%% Stimuli
s.near_d = .50;
s.near_name = 'Near-threshold';
s.pulse_t = 0.2;
s.pre_pulse_t = 1;
s.wave_t = 3; % ms [s.pre_pulse_t + s.TTL_t + x]
s.stim_dec = 2;
s.stim_max = 7;

s.TTL_t = 1;
s.TTL_V = 5;

%% Trial
s.get_flip_i = 200;
s.iti_t = [1.000 2.000]; % inter-trial interval in s
s.stimdelay_t = [0.6 0.8]; % stim delay interval in s
s.fix_t = 1; % how long is the fixation cross shown in s
s.stim_delay = 0.7; % time after cue till stimulation 
s.resp_window = 'variable';
s.resp1_max_t = 2.500; 
s.resp2_max_t = 2.500; 
s.resp_p_min_t = 0.0;
%% Screen design

s.window_color = [200 200 200];%[250 250 250]; % grey98 (very light grey)

%% Text
s.txt_color = [40 40 40]; % grey15-16 (anthracite)
s.txt_font = 'Arial';
s.txt_size = 105;
s.cue_size = 125;
s.blue_circle = [7 7 223];
s.orange_circle = [223 110 7]; % same luminance, same saturation as blue cirlce
%s.cue_color = [255 126 121]; % salmon
%s.cue_color = [217 95 2];
%s.cue_color = [205 38 38];

s.cue_color = [40 40 40]; %candy apple

s.likeli_color = [255 8 0]; %candy apple
s.feedback_color_correct = [34,139,34];
s.feedback_color_incorrect = [139 0 0];
%% Messages
s.fix = '+';
s.cue = '+';
s.resp1_txt = ['J'; 'N'];   % Ja - Nein
s.resp2_txt = ['S'; 'U'];   % Unsicher - Sicher
s.resp1_offset = 30;
s.pause_msg = '# Pause #\n\n\nWeiter mit beliebiger Taste';

%% Response Buttons

s.lpt_adr1 = '4FF8';% '378';
s.lpt_adr2 = '4FF4';% hex2dec(psi.lpt_adr1) + 1024
s.lpt_dir = 'bi';
s.debounceDelay = 0.025;
s.btn_resp1 = [3 4]; % [1 2];
s.btn_resp2 = [3 4]; % [1 2];
s.btn_esc = 2; % 3
%% Instruction
s.instr_dir = '/instr/';
s.instr_subdir_wildcard = 'condition_*';
s.instr_img_wildcard = 'Folie*.png';